font_size 13
font_family FiraCode Nerd Font Med
font_features Medium +cv02 +cv05 +cv09 +cv14 +ss04 +cv16 +cv31 +cv25 +cv26 +cv32 +cv28 +zero +onum  

tab_bar_min_tabs            2
tab_bar_edge                bottom
tab_bar_style               powerline
tab_bar_margin_width	    16
tab_powerline_style         round
window_padding_width	    16
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
cursor_shape                beam
cursor_trail                2

# BEGIN_KITTY_THEME
include rose-pine.conf
# END_KITTY_THEME
